Fix failures in CI testing
mozilla-services/autograph pull request #894
Opened 2024-04-26 20:38 UTC by oskirby

2024-04-26 23:56 UTC, hwine reviewed
I :love: the idea, but I'm clueless about some of the changes. Deferring to Jeff.

2024-04-27 01:32 UTC, jmhodges requested changes

2024-04-27 01:32 UTC, jmhodges commented on vendor/github.com/mozilla-services/autograph/verifier
It looks like you added the `replace` directive to `go.mod` and this symlink both. I think you just need the `replace`? (I tried reproducing behavior by deleting this symlink and running `go mod vendor` and then some `go build` in a few spots. But you mentioned some static analysis work, so I could be missing the right check)

2024-04-27 06:23 UTC, jmhodges commented on vendor/github.com/mozilla-services/autograph/verifier
Oh, it was `staticcheck` not working right? Strange.

2024-04-27 06:25 UTC, jmhodges approved these changes
LGTM!

Thank you so much!

I do wonder if, in a future patch, we wouldn't be better off getting rid of the nested go.mods, but I see [we have clients using the module](https://github.com/search?type=code&q=github.com%2Fmozilla-services%2Fautograph%2Fverifier%2Fcontentsignature) elsewhere.

2024-04-27 18:47 UTC, oskirby commented on vendor/github.com/mozilla-services/autograph/verifier
The thing I found is that removing the symlink and running `go mod vendor` causes go to rebuild the vendor directory, and it just re-creates a copy of `verifier/contentsignature` in `vendor/github.com/mozilla-services/autograph/verifier/contentsignature`.

So, all we have really done is update the vendored copy without removing it. It produces successful builds, but lays the foundation for more errors to creep in again by having two copies of the code.

The symlink isn't a great solution either though as it will just get blown away the next time someone tries a `go mod vendor` again.

2024-04-27 19:00 UTC, oskirby commented on vendor/github.com/mozilla-services/autograph/verifier
I think in this case staticcheck was working as expected, and the project was being built with the copy out of the vendor directory. The problem is, that version was old, and had begun to diverge from the copy in `verifier/contentsignature`

2024-05-01 17:57 UTC, merged

2024-05-01 17:58 UTC, jmhodges commented
Sorry for the delay on this merge. I wanted to get you collab rights, but we got distracted by yesterday's events